### PR TITLE
Add first version of application to predict through trained models

### PR DESCRIPTION
**Pull request by martinhoaragao**
Also change default model to 5 epochs and add 2 new trained models.

### CODE REVIEW

**Comment by FranciscoRibeiro** [comment]
Looks good :)

**Review by dinocosta — CHANGES_REQUESTED** [review]
@martinhoaragao Not actually requesting changes, just asking why did you gave up on uploading the logs? I think you explained it to me but I forgot 🤔

**Comment by FranciscoRibeiro** [comment]
@joaofcosta I think it was because he was habing trouble accessing the loss and accuracy parameters. It was one of the things he said he wanted to look into. I actually got "in charge" of checking that out, but I was already occupied with another task. Not sure if it answers your question :)

**Comment by martinhoaragao** [comment]
@joaofcosta haven't given up yet. Actually I was scared about the size of the models, but it seems that's really not an issue, not sure if that was what caused your confusion.

@FranciscoRibeiro is tasked with storing the loss and accuracy, possibly looking into a .csv file instead for easier analysis in order to update the log. I might end up picking it later depending on how things go. 
The idea would be for the menu where you select a trained model, to also show the accuracy and loss ideally. But that's really not important right now.

Right now my main goal is to figure out what is happening to the training, since the example that last model predicted was not what I was expecting at all!

**Comment by dinocosta** [comment]
@martinhoaragao Ok, accepting these changes :+1:

**Review by dinocosta — APPROVED** [review]

**Comment by dinocosta** [comment]
@martinhoaragao Ping on this, it is approved 😄

**Comment by martinhoaragao** [comment]
Will take care of it soon. As soon as I start working on this, I will first merge #7 here.
@joaofcosta

**Pull request merged**
